plugins {
	id 'java'
	id 'org.springframework.boot' version '3.5.16'
	id 'io.spring.dependency-management' version '1.1.7'
	id 'com.diffplug.spotless' version '7.2.1'
}

group = 'com.team3'
version = '0.0.1-SNAPSHOT'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(21)
	}
}

repositories {
	mavenCentral()
}

dependencies {
	implementation 'org.springframework.boot:spring-boot-starter-web'
	implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
	implementation 'org.springframework.boot:spring-boot-starter-validation'
	compileOnly 'org.projectlombok:lombok'
	runtimeOnly 'org.postgresql:postgresql'
	annotationProcessor 'org.projectlombok:lombok'
	testImplementation 'org.springframework.boot:spring-boot-starter-test'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

tasks.named('test') {
	useJUnitPlatform()
}

tasks.register('installGitHooks', Exec) {
	group = 'git'
	description = 'Configure Git hooks'
	commandLine 'git', 'config', 'core.hooksPath', '.githooks'

	doLast {
		fileTree('.githooks').forEach {
			it.setExecutable(true)
		}
		println 'Git hooks configured.'
	}
}

spotless {
  java {
	  googleJavaFormat('1.27.0')
	  removeUnusedImports()
	  formatAnnotations()
	  trimTrailingWhitespace()
	  endWithNewline()
  }
}
