CREATE TABLE retailers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(150) NOT NULL,
    country_code CHAR(2) NOT NULL,
    is_duty_free BOOLEAN NOT NULL,
    address VARCHAR(255),
    site_url TEXT,
    CONSTRAINT ck_retailers_country_supported CHECK (country_code IN ('KR', 'JP'))
);
