CREATE TABLE whiskies (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_id BIGINT NOT NULL,
    name VARCHAR(255) NOT NULL,
    volume_ml INTEGER NOT NULL,
    abv NUMERIC(5, 2),
    origin_id BIGINT,
    region_id BIGINT,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_whiskies_volume_positive CHECK (volume_ml > 0),
    CONSTRAINT ck_whiskies_abv_range CHECK (abv IS NULL OR (abv > 0 AND abv <= 100)),
    CONSTRAINT ck_whiskies_region_requires_origin CHECK (region_id IS NULL OR origin_id IS NOT NULL),
    CONSTRAINT fk_whiskies_category FOREIGN KEY (category_id)
        REFERENCES whisky_categories(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_whiskies_origin FOREIGN KEY (origin_id)
        REFERENCES whisky_origins(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_whiskies_region_origin FOREIGN KEY (region_id, origin_id)
        REFERENCES whisky_regions(id, origin_id) ON DELETE RESTRICT ON UPDATE RESTRICT
);

CREATE INDEX ix_whiskies_category_id ON whiskies(category_id);
CREATE INDEX ix_whiskies_origin_id ON whiskies(origin_id);
CREATE INDEX ix_whiskies_region_origin ON whiskies(region_id, origin_id);
