CREATE TABLE sale_products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    whisky_id BIGINT,
    retailer_id BIGINT NOT NULL,
    external_product_id VARCHAR(255) NOT NULL,
    raw_name VARCHAR(500) NOT NULL,
    raw_category VARCHAR(100),
    raw_spec VARCHAR(255),
    product_url TEXT NOT NULL,
    is_sold_out BOOLEAN,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_sale_products_retailer_external UNIQUE (retailer_id, external_product_id),
    CONSTRAINT fk_sale_products_whisky FOREIGN KEY (whisky_id)
        REFERENCES whiskies(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_sale_products_retailer FOREIGN KEY (retailer_id)
        REFERENCES retailers(id) ON DELETE RESTRICT ON UPDATE RESTRICT
);

CREATE INDEX ix_sale_products_whisky_id ON sale_products(whisky_id);
