CREATE TABLE whisky_aliases (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    whisky_id BIGINT NOT NULL,
    name VARCHAR(255) NOT NULL,
    CONSTRAINT uk_whisky_aliases_whisky_name UNIQUE (whisky_id, name),
    CONSTRAINT fk_whisky_aliases_whisky FOREIGN KEY (whisky_id)
        REFERENCES whiskies(id) ON DELETE CASCADE ON UPDATE RESTRICT
);

CREATE INDEX ix_whisky_aliases_name ON whisky_aliases(name);
