CREATE TABLE curations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE curation_whiskies (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    curation_id BIGINT NOT NULL,
    whisky_id BIGINT NOT NULL,
    CONSTRAINT pk_curation_whiskies PRIMARY KEY (id),
    CONSTRAINT uk_curation_whiskies_curation_whisky UNIQUE (curation_id, whisky_id),
    CONSTRAINT fk_curation_whiskies_curation FOREIGN KEY (curation_id)
        REFERENCES curations(id) ON DELETE CASCADE,
    CONSTRAINT fk_curation_whiskies_whisky FOREIGN KEY (whisky_id)
        REFERENCES whiskies(id) ON DELETE CASCADE
);

CREATE INDEX ix_curation_whiskies_whisky_id ON curation_whiskies(whisky_id);
