CREATE TABLE price_histories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sale_product_id BIGINT NOT NULL,
    price NUMERIC(18, 2) NOT NULL,
    currency_code CHAR(3) NOT NULL,
    collected_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_price_histories_product_collected UNIQUE (sale_product_id, collected_at),
    CONSTRAINT ck_price_histories_price_positive CHECK (price > 0),
    CONSTRAINT ck_price_histories_currency_supported CHECK (currency_code IN ('KRW', 'JPY', 'USD')),
    CONSTRAINT fk_price_histories_sale_product FOREIGN KEY (sale_product_id)
        REFERENCES sale_products(id) ON DELETE RESTRICT ON UPDATE RESTRICT
);
