CREATE TABLE collection_whiskies (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    collection_id BIGINT NOT NULL,
    whisky_id BIGINT NOT NULL,
    CONSTRAINT pk_collection_whiskies PRIMARY KEY (id),
    CONSTRAINT uk_collection_whiskies_collection_whisky UNIQUE (collection_id, whisky_id),
    CONSTRAINT fk_collection_whiskies_collection FOREIGN KEY (collection_id)
        REFERENCES collections(id) ON DELETE CASCADE,
    CONSTRAINT fk_collection_whiskies_whisky FOREIGN KEY (whisky_id)
        REFERENCES whiskies(id) ON DELETE CASCADE
);

CREATE INDEX ix_collection_whiskies_whisky_id ON collection_whiskies(whisky_id);
