ALTER TABLE users ADD COLUMN status VARCHAR(16) NOT NULL DEFAULT 'PENDING';

CREATE TABLE user_agreements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    agreement_type VARCHAR(32) NOT NULL,
    agreed BOOLEAN NOT NULL,
    agreed_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_user_agreements_user FOREIGN KEY (user_id)
        REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT uk_user_agreements_user_type UNIQUE (user_id, agreement_type)
);
