CREATE TABLE planners (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_planners_user FOREIGN KEY (user_id)
        REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT uk_planners_user UNIQUE (user_id)
);

CREATE TABLE planner_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    planner_id BIGINT NOT NULL,
    sale_product_id BIGINT NOT NULL,
    list_type VARCHAR(16) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_planner_items PRIMARY KEY (id),
    CONSTRAINT ck_planner_items_list_type CHECK (list_type IN ('PURCHASE', 'CANDIDATE')),
    CONSTRAINT fk_planner_items_planner FOREIGN KEY (planner_id)
        REFERENCES planners(id) ON DELETE CASCADE,
    CONSTRAINT fk_planner_items_sale_product FOREIGN KEY (sale_product_id)
        REFERENCES sale_products(id) ON DELETE RESTRICT ON UPDATE RESTRICT
);

CREATE INDEX ix_planner_items_planner_id ON planner_items(planner_id);
CREATE INDEX ix_planner_items_sale_product_id ON planner_items(sale_product_id);
