CREATE TABLE whisky_regions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    origin_id BIGINT NOT NULL,
    name VARCHAR(100) NOT NULL,
    CONSTRAINT uk_whisky_regions_origin_name UNIQUE (origin_id, name),
    CONSTRAINT uk_whisky_regions_id_origin UNIQUE (id, origin_id),
    CONSTRAINT fk_whisky_regions_origin FOREIGN KEY (origin_id)
        REFERENCES whisky_origins(id) ON DELETE RESTRICT ON UPDATE RESTRICT
);
